trigger: none  # Run manually only

variables:
    azureServiceConnection: 'ARM'
stages:
  - stage: CreateTerraformBackend
    displayName: "Create Terraform Backend Resources"
    jobs:
      - job: CreateBackend
        displayName: "Provision Resource Group, Storage Account, and Container"
        pool:
          name: Default
        steps:

          # Task 1: Create Resource Group
          - task: AzureCLI@2
            displayName: "Create Resource Group"
            inputs:
              azureSubscription: $(azureServiceConnection)  # Replace
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az group create \
                  --name JITHUSTORAGE-rg \
                  --location eastus

          # Task 2: Create Storage Account
          - task: AzureCLI@2
            displayName: "Create Storage Account"
            inputs:
              azureSubscription: $(azureServiceConnection)  # Replace
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az storage account create \
                  --name JITHUstatestorage \
                  --resource-group JITHUSTORAGE-rg \
                  --location eastus \
                  --sku Standard_LRS

          # Task 3: Get Storage Account Key
          - task: AzureCLI@2
            name: GetKey
            displayName: "Get Storage Account Key"
            inputs:
              azureSubscription: $(azureServiceConnection)  # Replace
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                ACCOUNT_KEY=$(az storage account keys list \
                  --resource-group JITHUSTORAGE-rg \
                  --account-name JITHUstatestorage \
                  --query '[0].value' \
                  --output tsv)
                echo "##vso[task.setvariable variable=ACCOUNT_KEY;issecret=true]$ACCOUNT_KEY"

          # Task 4: Create Container
          - task: AzureCLI@2
            displayName: "Create Blob Container for Terraform State"
            inputs:
              azureSubscription: $(azureServiceConnection)  # Replace
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az storage container create \
                  --name tfstate \
                  --account-name JITHUstatestorage \
                  --account-key $(ACCOUNT_KEY)
