trigger: none  # Run manually only

variables:
  azureServiceConnection: 'ARM'

stages:
  - stage: CreateTerraformBackend
    displayName: "Create Terraform Backend Resources"
    jobs:
      - job: CreateBackend
        displayName: "Provision Resource Group, Storage Account, and Container"
        pool:
          name: Default
        steps:

          - task: AzureCLI@2
            displayName: "Create Resource Group"
            inputs:
              azureSubscription: $(azureServiceConnection)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az group create \
                  --name pratheekSTORAGE-rg \
                  --location japanwest

          - task: AzureCLI@2
            displayName: "Create Storage Account"
            inputs:
              azureSubscription: $(azureServiceConnection)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az storage account create \
                  --name pratheekstorage \
                  --resource-group pratheekSTORAGE-rg \
                  --location japanwest \
                  --sku Standard_LRS

          - task: AzureCLI@2
            name: GetKey
            displayName: "Get Storage Account Key"
            inputs:
              azureSubscription: $(azureServiceConnection)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                ACCOUNT_KEY=$(az storage account keys list \
                  --resource-group pratheekSTORAGE-rg \
                  --account-name pratheekstorage \
                  --query '[0].value' \
                  --output tsv)
                echo "##vso[task.setvariable variable=ACCOUNT_KEY;issecret=true]$ACCOUNT_KEY"

          - task: AzureCLI@2
            displayName: "Create Blob Container for Terraform State"
            inputs:
              azureSubscription: $(azureServiceConnection)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az storage container create \
                  --name tfstate \
                  --account-name pratheekstorage \
                  --account-key $(ACCOUNT_KEY)
