trigger: none  # manual only

pool:
  name: Default

variables:
  terraformDirectory: '.'         
  azureServiceConnection: 'ARM'   
  terraformVersion: '1.7.5'       

stages:
  - stage: Terraform
    displayName: 'Terraform Deployment Stage'
    jobs:
      - job: TerraformJob
        displayName: 'Run Terraform Commands'
        steps:

          - task: TerraformInstaller@1
            displayName: 'Install Terraform'
            inputs:
              terraformVersion: $(terraformVersion)

          - task: AzureCLI@2
            displayName: 'Terraform Init'
            inputs:
              azureSubscription: $(azureServiceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              workingDirectory: $(terraformDirectory)
              inlineScript: |
                terraform init -upgrade -input=false

          - task: AzureCLI@2
            displayName: 'Terraform Validate'
            inputs:
              azureSubscription: $(azureServiceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              workingDirectory: $(terraformDirectory)
              inlineScript: |
                terraform validate

          - task: AzureCLI@2
            displayName: 'Terraform Plan'
            inputs:
              azureSubscription: $(azureServiceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              workingDirectory: $(terraformDirectory)
              inlineScript: |
                terraform plan -out=tfplan

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Terraform Plan Artifact'
            inputs:
              PathtoPublish: '$(terraformDirectory)/tfplan'
              ArtifactName: 'tfplan'
              publishLocation: 'Container'

          - task: AzureCLI@2
            displayName: 'Terraform Apply'
            inputs:
              azureSubscription: $(azureServiceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              workingDirectory: $(terraformDirectory)
              inlineScript: |
                terraform apply -auto-approve tfplan
